name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Clean
        run: dotnet clean $env:GITHUB_WORKSPACE\EvernoteToNotionChrome.sln --configuration Release && dotnet nuget locals all --clear
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run:  dotnet publish -c Release -r win-x64
      - run: powershell curl https://github.com/aiqinxuancai/DotNetDllPathPatcherWPF/releases/download/v0.0.15/DotNetDllPathPatcherCMD.zip -o DotNetDllPathPatcherCMD.zip
      - run: powershell Expand-Archive -Path .\DotNetDllPathPatcherCMD.zip -DestinationPath .\DotNetDllPathPatcherCMD
      - run: powershell .\DotNetDllPathPatcherCMD\publish\DotNetDllPathPatcherCMD.exe $env:GITHUB_WORKSPACE\EvernoteToNotionChrome\bin\Release\net7.0-windows\win-x64\publish\EvernoteToNotionChrome.exe
      - name: Compress
        run: powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\EvernoteToNotionChrome\bin\Release\net7.0-windows\win-x64\publish -DestinationPath .\EvernoteToNotionChrome.zip
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "EvernoteToNotionChrome.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
