name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
      - name: Clean
        run: dotnet clean $env:GITHUB_WORKSPACE\HTMLToNotion\HTMLToNotion.csproj --configuration Release && dotnet nuget locals all --clear
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run:  dotnet publish -c Release --runtime win-x64 --self-contained=true
      - run: powershell curl https://github.com/aiqinxuancai/DotNetDllPathPatcherWPF/releases/download/v0.0.15/DotNetDllPathPatcherCMD.zip -o DotNetDllPathPatcherCMD.zip
      - run: powershell Expand-Archive -Path .\DotNetDllPathPatcherCMD.zip -DestinationPath .\DotNetDllPathPatcherCMD
      - run: powershell .\DotNetDllPathPatcherCMD\publish\DotNetDllPathPatcherCMD.exe $env:GITHUB_WORKSPACE\HTMLToNotion\bin\Release\net9.0-windows\win-x64\publish\HTMLToNotion.exe
      - name: Compress
        run: powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\HTMLToNotion\bin\Release\net9.0-windows\win-x64\publish -DestinationPath .\HTMLToNotion.zip
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "HTMLToNotion.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
